export const orderSheetMockData = [
  {
    order_id: 1,
    order_number: "ORD001",
    order_status: "order_placed",
    created_at: "2026-07-08T10:00:00",
    items: [
      {
        order_item_id: 11,
        menu_item_id: 101,
        item_name: "Paneer Tikka",
        quantity: 1,
        unit_price: 280,
        total_price: 280,
        item_status: "order_placed",
        image_url: "",
      },
      {
        order_item_id: 12,
        menu_item_id: 1013,
        item_name: "Paneer Tikka",
        quantity: 1,
        unit_price: 280,
        total_price: 280,
        item_status: "ready",
        image_url: "",
      },
    ],
  },
  {
    order_id: 2,
    order_number: "ORD002",
    order_status: "preparing",
    created_at: "2026-07-08T10:05:00",
    items: [
      {
        order_item_id: 12,
        menu_item_id: 102,
        item_name: "Veg Noodles",
        quantity: 2,
        unit_price: 180,
        total_price: 360,
        item_status: "preparing",
        image_url: "",
      },
    ],
  },
  {
    order_id: 3,
    order_number: "ORD003",
    order_status: "ready",
    created_at: "2026-07-08T10:10:00",
    items: [
      {
        order_item_id: 13,
        menu_item_id: 103,
        item_name: "Masala Dosa ready",
        quantity: 3,
        unit_price: 120,
        total_price: 360,
        item_status: "ready",
        image_url: "",
      },
      {
        order_item_id: 13,
        menu_item_id: 103,
        item_name: "Masala Dosa served",
        quantity: 3,
        unit_price: 120,
        total_price: 360,
        item_status: "served",
        image_url: "",
      },
    ],
  },
];

export const orderSheetSortMockData = [
  {
    order_id: 1,
    order_number: "ORD001",
    order_status: "served",
    created_at: "2026-07-08T10:00:00",
    items: [
      {
        order_item_id: 11,
        menu_item_id: 101,
        item_name: "Served Item",
        quantity: 1,
        unit_price: 280,
        total_price: 280,
        item_status: "served",
        image_url: "",
      },
    ],
  },
  {
    order_id: 2,
    order_number: "ORD002",
    order_status: "order_placed",
    created_at: "2026-07-08T10:05:00",
    items: [
      {
        order_item_id: 12,
        menu_item_id: 102,
        item_name: "Placed Item",
        quantity: 2,
        unit_price: 180,
        total_price: 360,
        item_status: "order_placed",
        image_url: "",
      },
    ],
  },
  {
    order_id: 3,
    order_number: "ORD003",
    order_status: "preparing",
    created_at: "2026-07-08T10:10:00",
    items: [
      {
        order_item_id: 13,
        menu_item_id: 103,
        item_name: "Preparing Item",
        quantity: 3,
        unit_price: 120,
        total_price: 360,
        item_status: "preparing",
        image_url: "",
      },
    ],
  },
  {
    order_id: 4,
    order_number: "ORD004",
    order_status: "ready",
    created_at: "2026-07-08T10:15:00",
    items: [
      {
        order_item_id: 14,
        menu_item_id: 104,
        item_name: "Ready Item",
        quantity: 1,
        unit_price: 200,
        total_price: 200,
        item_status: "ready",
        image_url: "",
      },
    ],
  },
];
